name: number_puzzles
description: A new Flutter project.
publish_to: "none"
version: 0.1.9+9

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  confetti: ^0.7.0
  google_fonts: ^6.1.0
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  dio: ^5.3.4
  audioplayers: ^5.2.1
  connectivity_plus: ^5.0.2
  intro_screen_onboarding_flutter: ^1.0.0
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^3.1.0
  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
